language: python

sudo: false

python:
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip wheel codecov
  - make dev

before_script:
  - createdb -E UTF-8 secretcards -U postgres -O $USER

script:
  - make

after_success:
  - codecov

branches:
  only:
    - master
